### ISSUE TITLE
We love good git flow!

### ISSUE THREAD

**Issue by matthewdking** [FACN3/HIS_node#26]
**Issues**
Awesome, lots of issues with descriptions. I would say a lot of the issues are very small and some could be joined together.

**Commits**
I :heart: seeing _almost all_ of your commits linked to issues. They _mostly_ all have descriptive messages so I know what you did which is great :1st_place_medal:.

**Pull Requests**
You guys are linking your pull requests to issues :+1:. Just a minor point on this, you can't link to issues in the title of the PR so in future you only need it in the description rather than the title. PRs should be reviewed by your team members before you merge. You should assign your team as reviewers where they can approve :white_check_mark: , request changes :x:  or just ask questions :question:  about specific parts of the code they don't understand. The final reviewer should merge the PR. I understand in a small team like this it may seem like a waste of time but it is a good way to ensure the whole team understands the code.

**Contributions**
It would be great to see a more equal spread of contributions between team members on the [graph](https://github.com/FACN3/HIS_node/graphs/contributors) :chart_with_upwards_trend: . Keep swapping who is typing and the laptop you are working on throughout the project :star:.

**Comment by idantb101** [comment]
@matthewdking Thanks :bowtie:
and please notice that in pull req we put the issue inside the req as well as
 in the title.
