### ISSUE TITLE
We also love good READMEs yay

### ISSUE THREAD

**Issue by finnhodgkin** [FACN3/HIS_node#35]
The readme looks great :100: A few minor notes though:

In the installation instructions you have some markdown within backticks `## like this`. I'm guessing that was just a mistake.

There's also this line in the readme:

https://github.com/FACN3/HIS_node (needs to be changed)

Which should probably just be removed. You explain how to use the project below including cloning the repo so there isn't really a need for this.

**Comment by idantb101** [comment]
fixed
