### ISSUE TITLE
Auto Complete words

### ISSUE THREAD

**Issue by Amirk390** [FACN3/HIS_node#39]
Apparently the auto complete words are always starting with 'O'

and it only shows the same 10 words: :sweat: 

- Obama
- Obama, Fukui
- Obama Doctrine
- Obama (genus)
- Obama Anak Menteng
- Obama nungara
- Obama logo
- Obama Domain
- Obamadon
- Obama Zombies

**Comment by idantb101** [comment]
fixed.
