### ISSUE TITLE
.vscode should be .gitignored

### ISSUE THREAD

**Issue by finnhodgkin** [FACN3/HIS_node#40]
It's a vscode specific file that isn't necessary to run the project so should probably be in the `.gitignore`. The master branch should _only_ contain files necessary to run the project.

**Comment by idantb101** [comment]
it is a dependency to debug the app in all users who clone it. 
shouldn't it be on git as package.json is for packages.

**Comment by finnhodgkin** [comment]
If you really think it's necessary, but I would say your project should be debug-able by users in _every_ text editor. Up to you.
