### ISSUE TITLE
README assets should be stored in issues

### ISSUE THREAD

**Issue by finnhodgkin** [FACN3/HIS_node#42]
You have an assets folder with images that are readme specific. These should be hosted in issues rather than the repository to to stop users who want to clone your project from having to download them.

Happy to show you the process for this :+1:

**Comment by idantb101** [comment]
![planimage](https://user-images.githubusercontent.com/20503536/33242239-4b9d4e78-d2da-11e7-967c-9ef9dbfac0a5.jpeg)

**Comment by idantb101** [comment]
![process](https://user-images.githubusercontent.com/20503536/33242248-64177230-d2da-11e7-9cdb-b93eb72b9c21.jpeg)

**Comment by idantb101** [comment]
fixed.
