### ISSUE TITLE
Redundant function in server.js

### ISSUE THREAD

**Issue by finnhodgkin** [FACN3/HIS_node#46]
```js
const router = require('./router');

var app = function (request, response) {
    router(request, response);
};

http.createServer(app).listen(port);
```

Is functionally the same as:

```js
const router = require('./router');

http.createServer(router).listen(port)
```

**Comment by idantb101** [comment]
currently my server console.log the port, so i could see it is not crashes.


`const app =  (request, response) => {
    console.log('server listening on port http://localhost:', port);
    router(request, response);
};`


should i just log it in the router ? would it make sense ?

**Comment by idantb101** [comment]
fixed,
