### ISSUE TITLE
Replace the for loop

### ISSUE THREAD

**Issue by finnhodgkin** [FACN3/HIS_node#54]
In model.js you have a for loop that could be replaced with something like this if you wanted (die for loops die):

```js
const result = Array.from({length:10}, (el, index) => {
  return {
    title: parsedData[1][index],
    link: parsedData[3][index]
  };
});
```

I usually only recommend for loops when `break` is necessary.

**Comment by idantb101** [comment]
please review my changes. :) @finnhodgkin

**Comment by finnhodgkin** [comment]
I'd remove the commented out for but otherwise looks good :+1:
